# ref: https://docs.travis-ci.com/user/languages/python
# note: the docker build goes to dizz as the credentials for elastest are not available yet
language: python

python:
  - "3.6"

sudo: required

install:
  - "pip install -r src/requirements.txt"
  - "pip install -r tests/test-requirements.txt"
  - "pip install codecov"  # only for use on travis

env:
  - MONGODB_TESTS=YES MYSQL_TESTS=YES DOCKER_TESTS=YES

before_script:
  - sleep 15
  - docker network create elastest

script:
  - nosetests --with-xunit --with-coverage --cover-erase --cover-package=adapters --cover-package=esm --cover-min-percentage=70
  - docker build -t dizz/esm .
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

services:
  - docker
  - mongodb
  - mysql

after_success:
  - codecov
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push dizz/esm;
    fi
