# ref: https://docs.travis-ci.com/user/languages/python
# note: the docker build goes to dizz as the credentials for elastest are not available yet
language: python

python:
  - "3.6"

cache: pip

sudo: required

services:
  - docker

env:
  - DOCKER_TESTS=YES MONGODB_TESTS=YES EPM_TESTS=YES ET_EPM_API=http://localhost:8180/ ESM_DOCKER_DELETE_TIMEOUT=1 ESM_MONGO_HOST=localhost

install:
  - docker-compose -f tests/docker/docker-compose-travis-deps.yml up -d
  - pip install -r src/requirements.txt
  - pip install -r tests/requirements.txt

before_script:
  - sleep 15

script:
  - nosetests --with-xunit --with-coverage --cover-erase --cover-package=adapters --cover-package=esm --cover-min-percentage=70
  - docker build -t dizz/esm .
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

after_success:
  - docker-compose -f tests/docker/docker-compose-local-deps.yml down -v
  - codecov
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push dizz/esm;
    fi
