version: '3'

services:
  tester:
    build:
      context: ./
      dockerfile: ./Dockerfile-tester
    depends_on:
      - mongo
      - mysql
      - epm
      - epm-dca
      - aaa
    image: elastest/esm-tester:latest
    container_name: tester
    hostname: tester
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - ./:/output:rw
    environment:
      - DOCKER_TESTS=NO
      - MONGODB_TESTS=YES
      - MYSQL_TESTS=NO
      - HEARTBEAT_TESTS=YES
      - EPM_TESTS=YES
      - BINDING_TESTS=YES
      - SENTINEL_TESTS=NO
      - ESM_MONGO_HOST=mongo
#      - ET_EDM_MYSQL_HOST=mysql
#      - ESM_SQL_PASSWORD=shush
      - ET_EPM_API=http://epm:8180/
      - ET_AAA_ESM_KEYSTONE_BASE_URL=http://aaa
      - ET_AAA_ESM_KEYSTONE_USERNAME=admin
      - ET_AAA_ESM_KEYSTONE_PASSWD=admin
      - ET_AAA_ESM_KEYSTONE_TENANT=admin
    networks:
      - elastest_elastest

  aaa:
    depends_on:
      - mysql
    image: dizz/dock-os-keystone
    hostname: aaa
    container_name: aaa
    links:
      - mysql
    ports:
      - "35357:35357"
      - "5000:5000"
    environment:
      MYSQL_HOST: mysql
      MYSQL_ROOT_PASSWORD: shush
      ADMIN_TOKEN: admintokin
      ADMIN_TENANT_NAME: admin
      ADMIN_USER_NAME: admin
      ADMIN_PASSWORD: admin
    networks:
      - elastest_elastest

  mongo:
    image: mongo:latest
    container_name: mongo
    hostname: mongo
    ports:
      - "27017"
    networks:
      - elastest_elastest

  mysql:
    image: mysql:5.7
    container_name: mysql
    hostname: mysql
    environment:
      MYSQL_ROOT_PASSWORD: shush
    ports:
      - "3306"
    networks:
      - elastest_elastest

  epm:
    container_name: epm
    image: elastest/epm
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock:rw
    expose:
        - 8180
    ports:
        - 8180:8180
    networks:
        - elastest_elastest

  epm-dca:
    container_name: epm-dca
    image: elastest/epm-adapter-docker-compose
    entrypoint: python run.py --register-adapter epm epm-dca
    depends_on:
        - epm
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock:rw
    expose:
        - 50051
    ports:
        - 50051:50051
    networks:
        - elastest_elastest

networks:
    elastest_elastest:
      driver: bridge
