version: '3'

services:
  tester:
    build:
      context: ./
      dockerfile: ./Dockerfile-tester
    depends_on:
      - mongo
      - mysql
      - epm
      - epm-dca
    image: elastest/esm-tester:latest
    container_name: tester
    hostname: tester
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - ./:/output:rw
    environment:
      - DOCKER_TESTS=NO
      - MONGODB_TESTS=YES
      - MYSQL_TESTS=YES
      - HEARTBEAT_TESTS=YES
      - EPM_TESTS=NO
      - BINDING_TESTS=NO
      - SENTINEL_TESTS=NO
      - ESM_MONGO_HOST=mongo
      - ET_EDM_MYSQL_HOST=mysql
      - ET_EPM_API=http://epm:8180/
    networks:
      - elastest_elastest

  mongo:
    image: mongo:latest
    container_name: mongo
    hostname: mongo
    ports:
      - "27017"
    networks:
      - elastest_elastest

  mysql:
    image: mysql:latest
    container_name: mysql
    hostname: mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "3306"
    networks:
      - elastest_elastest

  epm:
    container_name: epm
    image: elastest/epm
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock:rw
    expose:
        - 8180
    ports:
        - 8180:8180
    networks:
        - elastest_elastest

  epm-dca:
    container_name: epm-dca
    image: elastest/epm-adapter-docker-compose
    entrypoint: python run.py --register-adapter
    depends_on:
        - epm
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock:rw
    expose:
        - 50051
    ports:
        - 50051:50051
    networks:
        - elastest_elastest

networks:
    elastest_elastest:
      driver: bridge
