FROM gliderlabs/alpine:latest

LABEL maintainer="elastest-users@googlegroups.com"
LABEL description="Tests the service manager code base."

RUN mkdir /output
WORKDIR /app
COPY . /app

RUN apk --update add python3 py3-pip openssl ca-certificates git python3-dev build-base linux-headers \
    && pip3 install --upgrade setuptools pip tox

CMD tox -c tox-tester.ini
