version: '2.1'

services:

## ESM Containers
  esm:
    build:
      context: ./
      dockerfile: ./Dockerfile-all
    depends_on:
      - mongo
      - epm
      - epm-dca
      - aaa
    image: elastest/esm:latest
    command: tox -c tox-tester.ini
    container_name: esm
    hostname: esm
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - ./:/output:rw
    environment:
      # testing params
      - DOCKER_TESTS=YES
      - MONGODB_TESTS=YES
      - EPM_TESTS=YES
      - BINDING_TESTS=YES
      - MYSQL_TESTS=NO
      - HEARTBEAT_TESTS=NO
      - SENTINEL_TESTS=NO
      # execution params, also required for testing
      - ESM_PORT=37005
      - ESM_CHECK_PORT=5001
      - ESM_DOCKER_DELETE_TIMEOUT=1  # low for quicker test runs
      - ESM_MONGO_HOST=mongo
      - ET_EPM_API=http://epm:8180/
      - ET_AAA_ESM_KEYSTONE_BASE_URL=http://aaa
      - ET_AAA_ESM_KEYSTONE_USERNAME=admin
      - ET_AAA_ESM_KEYSTONE_PASSWD=admin
      - ET_AAA_ESM_KEYSTONE_TENANT=admin
      - ESM_MEASURE_INSTANCES=NO
#      - ET_EDM_MYSQL_HOST=mysql
#      - ESM_SQL_PASSWORD=shush
#      - ET_EMP_API=http://emp:9100
#      - ESM_SENTINEL_KAFKA_ENDPOINT=emp-kafka:9092
#      - ESM_SENTINEL_TOPIC=topic
#      - ESM_SENTINEL_SERIES_NAME=name

    networks:
      - elastest_elastest

  mongo:
    image: mongo:latest
    container_name: mongo
    hostname: mongo
    ports:
      - "27017"
    networks:
      - elastest_elastest

## AAA Containers
  aaa:
    depends_on:
      mysql:
        condition: service_healthy
    image: dizz/dock-os-keystone
    hostname: aaa
    container_name: aaa
    links:
      - mysql
    ports:
      - "35357:35357"
      - "5000:5000"
    environment:
      MYSQL_HOST: mysql
      MYSQL_ROOT_PASSWORD: shush
      ADMIN_TOKEN: admintokin
      ADMIN_TENANT_NAME: admin
      ADMIN_USER_NAME: admin
      ADMIN_PASSWORD: admin
    networks:
      - elastest_elastest

  mysql:
    image: mysql:5.7
    container_name: mysql
    hostname: mysql
    environment:
      MYSQL_ROOT_PASSWORD: shush
    ports:
      - "3306"
    healthcheck:  # required in order to signal correct startup to dependent services (see aaa)
      test: "/usr/bin/mysql --user=root --password=shush --execute \"show databases;\""
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      - elastest_elastest

## EPM Containers
  epm:
    container_name: epm
    image: elastest/epm
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock:rw
    expose:
        - 8180
    ports:
        - 8180:8180
    networks:
        - elastest_elastest

  epm-dca:
    container_name: epm-dca
    image: elastest/epm-adapter-docker-compose
    entrypoint: python run.py --register-adapter epm epm-dca
    depends_on:
        - epm
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock:rw
    expose:
        - 50051
    ports:
        - 50051:50051
    networks:
        - elastest_elastest

networks:
    elastest_elastest:
      driver: bridge
