node('docker'){
    stage "Container Prep"
        def mycontainer = docker.image('elastest/ci-docker-compose-py-siblings:latest')
        mycontainer.pull() // make sure we have the latest available from Docker Hub

        mycontainer.inside("-u jenkins -v /var/run/docker.sock:/var/run/docker.sock:rw") {

            git 'https://github.com/elastest/elastest-service-manager'

            stage ("ESM Service"){
                echo ("Starting ESM service...")
                sh "docker-compose -f tests/e2e/docker-compose-tester-integration-deps.yml up --build
            }
            stage ("ESM E2E Test"){

            }

            stage ("ESM report and cleanup"){
                step([$class: 'JUnitResultArchiver', testResults: '**/nosetests.xml'])
                sh "docker-compose -f tests/e2e/docker-compose-tester-integration-deps.yml down -v"
            }
        }
}
