node('docker'){
    stage "Container Prep"
        def mycontainer = docker.image('elastest/ci-docker-compose-py-siblings:latest')
        mycontainer.pull() // make sure we have the latest available from Docker Hub

        mycontainer.inside("-u jenkins -v /var/run/docker.sock:/var/run/docker.sock:rw") {

            git 'https://github.com/elastest/elastest-service-manager'

            stage ("ESM Service"){
                echo ("Starting ESM service...")
                sh "docker-compose -f tests/e2e/docker-compose.yml up --build -d"
            }
            stage ("ESM E2E Test"){
                esmIP = sh (
                     script: 'docker inspect --format=\\"{{.NetworkSettings.Networks.e2e_elastest_elastest.IPAddress}}\\" esm',
                     returnStdout: true
                 ).trim()
                esmIP = esmIP.substring(1, esmIP.length()-1)
                echo "ESM container IP=${esmIP}"

                sh "docker run -it --network e2e_elastest_elastest   -e ESM_EP_IP=${esmIP} dizz/esm_e2e:latest"
            }

            stage ("ESM E2E cleanup"){
                // step([$class: 'JUnitResultArchiver', testResults: '**/nosetests.xml'])
                sh "docker-compose -f tests/e2e/docker-compose-tester-integration-deps.yml down -v"
            }
        }
}
