version: '2.1'

services:
  esm:
    depends_on:
      - mongo
    image: elastest/esm:latest
    container_name: esm
    hostname: esm
    environment:
      - ESM_PORT=8080
      - ESM_MONGO_HOST=mongo  # the mongo service
    ports:
      - "8080:8080"

  mongo:
    image: mongo
    container_name: mongo
    hostname: mongo
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017"
volumes:
  mongo-data:
    driver: local
