# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class DashboardUrl(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, dashboard_url: str=None, operation: str=None):
        """
        DashboardUrl - a model defined in Swagger

        :param dashboard_url: The dashboard_url of this DashboardUrl.
        :type dashboard_url: str
        :param operation: The operation of this DashboardUrl.
        :type operation: str
        """
        self.swagger_types = {
            'dashboard_url': str,
            'operation': str
        }

        self.attribute_map = {
            'dashboard_url': 'dashboard_url',
            'operation': 'operation'
        }

        self._dashboard_url = dashboard_url
        self._operation = operation

    @classmethod
    def from_dict(cls, dikt) -> 'DashboardUrl':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DashboardUrl of this DashboardUrl.
        :rtype: DashboardUrl
        """
        return deserialize_model(dikt, cls)

    @property
    def dashboard_url(self) -> str:
        """
        Gets the dashboard_url of this DashboardUrl.
        \"The URL of a web-based management user interface for the service instance; we refer to this as a service dashboard. The URL should contain enough information for the dashboard to identify the resource being accessed (in the example below). For information on how users can authenticate with service dashboards via SSO.\" 

        :return: The dashboard_url of this DashboardUrl.
        :rtype: str
        """
        return self._dashboard_url

    @dashboard_url.setter
    def dashboard_url(self, dashboard_url: str):
        """
        Sets the dashboard_url of this DashboardUrl.
        \"The URL of a web-based management user interface for the service instance; we refer to this as a service dashboard. The URL should contain enough information for the dashboard to identify the resource being accessed (in the example below). For information on how users can authenticate with service dashboards via SSO.\" 

        :param dashboard_url: The dashboard_url of this DashboardUrl.
        :type dashboard_url: str
        """

        self._dashboard_url = dashboard_url

    @property
    def operation(self) -> str:
        """
        Gets the operation of this DashboardUrl.
        \"For async responses, service brokers can return operation state as a string. This field will be provided back to the service broker on last_operation requests as a URL encoded query param.\" 

        :return: The operation of this DashboardUrl.
        :rtype: str
        """
        return self._operation

    @operation.setter
    def operation(self, operation: str):
        """
        Sets the operation of this DashboardUrl.
        \"For async responses, service brokers can return operation state as a string. This field will be provided back to the service broker on last_operation requests as a URL encoded query param.\" 

        :param operation: The operation of this DashboardUrl.
        :type operation: str
        """

        self._operation = operation

