# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class Error(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, description: str=None):
        """
        Error - a model defined in Swagger

        :param description: The description of this Error.
        :type description: str
        """
        self.swagger_types = {
            'description': str
        }

        self.attribute_map = {
            'description': 'description'
        }

        self._description = description

    @classmethod
    def from_dict(cls, dikt) -> 'Error':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Error of this Error.
        :rtype: Error
        """
        return deserialize_model(dikt, cls)

    @property
    def description(self) -> str:
        """
        Gets the description of this Error.
        \"An error message explaining why the request failed. This message will be displayed to the user who initiated the request.\" 

        :return: The description of this Error.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """
        Sets the description of this Error.
        \"An error message explaining why the request failed. This message will be displayed to the user who initiated the request.\" 

        :param description: The description of this Error.
        :type description: str
        """

        self._description = description

