# coding: utf-8

from __future__ import absolute_import
#
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class Parameter(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, name: str=None, value: object=None):
        """
        Parameter - a model defined in Swagger

        :param name: The name of this Parameter.
        :type name: str
        :param value: The value of this Parameter.
        :type value: object
        """
        self.swagger_types = {
            'name': str,
            'value': object
        }

        self.attribute_map = {
            'name': 'name',
            'value': 'value'
        }

        self._name = name
        self._value = value

    @classmethod
    def from_dict(cls, dikt) -> 'Parameter':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Parameter of this Parameter.
        :rtype: Parameter
        """
        return deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """
        Gets the name of this Parameter.
        Name of the parameter

        :return: The name of this Parameter.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """
        Sets the name of this Parameter.
        Name of the parameter

        :param name: The name of this Parameter.
        :type name: str
        """

        self._name = name

    @property
    def value(self) -> object:
        """
        Gets the value of this Parameter.
        value of the parameter

        :return: The value of this Parameter.
        :rtype: object
        """
        return self._value

    @value.setter
    def value(self, value: object):
        """
        Sets the value of this Parameter.
        value of the parameter

        :param value: The value of this Parameter.
        :type value: object
        """

        self._value = value

