# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class Listing(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, blurb: str=None, image_url: str=None, long_description: str=None):
        """
        Listing - a model defined in Swagger

        :param blurb: The blurb of this Listing.
        :type blurb: str
        :param image_url: The image_url of this Listing.
        :type image_url: str
        :param long_description: The long_description of this Listing.
        :type long_description: str
        """
        self.swagger_types = {
            'blurb': str,
            'image_url': str,
            'long_description': str
        }

        self.attribute_map = {
            'blurb': 'blurb',
            'image_url': 'imageUrl',
            'long_description': 'longDescription'
        }

        self._blurb = blurb
        self._image_url = image_url
        self._long_description = long_description

    @classmethod
    def from_dict(cls, dikt) -> 'Listing':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Listing of this Listing.
        :rtype: Listing
        """
        return deserialize_model(dikt, cls)

    @property
    def blurb(self) -> str:
        """
        Gets the blurb of this Listing.
        blurb

        :return: The blurb of this Listing.
        :rtype: str
        """
        return self._blurb

    @blurb.setter
    def blurb(self, blurb: str):
        """
        Sets the blurb of this Listing.
        blurb

        :param blurb: The blurb of this Listing.
        :type blurb: str
        """

        self._blurb = blurb

    @property
    def image_url(self) -> str:
        """
        Gets the image_url of this Listing.
        image URL.

        :return: The image_url of this Listing.
        :rtype: str
        """
        return self._image_url

    @image_url.setter
    def image_url(self, image_url: str):
        """
        Sets the image_url of this Listing.
        image URL.

        :param image_url: The image_url of this Listing.
        :type image_url: str
        """

        self._image_url = image_url

    @property
    def long_description(self) -> str:
        """
        Gets the long_description of this Listing.
        Long Description

        :return: The long_description of this Listing.
        :rtype: str
        """
        return self._long_description

    @long_description.setter
    def long_description(self, long_description: str):
        """
        Sets the long_description of this Listing.
        Long Description

        :param long_description: The long_description of this Listing.
        :type long_description: str
        """

        self._long_description = long_description

