# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class UpdateOperationResponse(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, operation: str=None):
        """
        UpdateOperationResponse - a model defined in Swagger

        :param operation: The operation of this UpdateOperationResponse.
        :type operation: str
        """
        self.swagger_types = {
            'operation': str
        }

        self.attribute_map = {
            'operation': 'operation'
        }

        self._operation = operation

    @classmethod
    def from_dict(cls, dikt) -> 'UpdateOperationResponse':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The UpdateOperationResponse of this UpdateOperationResponse.
        :rtype: UpdateOperationResponse
        """
        return deserialize_model(dikt, cls)

    @property
    def operation(self) -> str:
        """
        Gets the operation of this UpdateOperationResponse.
        For asynchronous responses, service brokers MAY return an identifier representing the operation. The value of this field MUST be provided by the platform with requests to the Last Operation endpoint in a URL encoded query parameter. If present, MUST be a non-empty string. 

        :return: The operation of this UpdateOperationResponse.
        :rtype: str
        """
        return self._operation

    @operation.setter
    def operation(self, operation: str):
        """
        Sets the operation of this UpdateOperationResponse.
        For asynchronous responses, service brokers MAY return an identifier representing the operation. The value of this field MUST be provided by the platform with requests to the Last Operation endpoint in a URL encoded query parameter. If present, MUST be a non-empty string. 

        :param operation: The operation of this UpdateOperationResponse.
        :type operation: str
        """

        self._operation = operation

