# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class UpdateOperation(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, operation: str=None):
        """
        UpdateOperation - a model defined in Swagger

        :param operation: The operation of this UpdateOperation.
        :type operation: str
        """
        self.swagger_types = {
            'operation': str
        }

        self.attribute_map = {
            'operation': 'operation'
        }

        self._operation = operation

    @classmethod
    def from_dict(cls, dikt) -> 'UpdateOperation':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The UpdateOperation of this UpdateOperation.
        :rtype: UpdateOperation
        """
        return deserialize_model(dikt, cls)

    @property
    def operation(self) -> str:
        """
        Gets the operation of this UpdateOperation.
        \"For async responses, service brokers can return operation state as a string. This field will be provided back to the service broker on `last_operation` requests as a URL encoded query param.\" 

        :return: The operation of this UpdateOperation.
        :rtype: str
        """
        return self._operation

    @operation.setter
    def operation(self, operation: str):
        """
        Sets the operation of this UpdateOperation.
        \"For async responses, service brokers can return operation state as a string. This field will be provided back to the service broker on `last_operation` requests as a URL encoded query param.\" 

        :param operation: The operation of this UpdateOperation.
        :type operation: str
        """

        self._operation = operation

